# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to github docker Registry
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Set the image tag
        id: image_vars
        run: |
          REPO=${{ github.repository }}
          TAG=latest
          echo ::set-output name=repo::$(echo $REPO | awk '{print tolower($0)}')
          echo ::set-output name=tag::$(echo $TAG | awk '{print tolower($0)}')

      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew distDocker -PdockerRegistry=ghcr.io -PdockerImagePrefix=${{steps.image_vars.outputs.repo}} -PdockerImageTag=${{steps.image_vars.outputs.tag}}